# Q1. What are the benefits of the built-in array package, if any?



<li>built in arrrays are useful when we are required to manipulate only a specific data type values</li>

# Q2. What are some of the array package's limitations?


<li>arrays are homogenous and can contain object of only one type

# Q3. Describe the main differences between the array and numpy packages.


<li> Numpy arrays are used for performing advanced arithmetic operations on homogeneous Items, e,g the Matrix operations can be applied.
<li>Built-in arrays are good if you want to use basic arithmetic operations on a list of elements.

# Q4. Explain the distinctions between the empty, ones, and zeros functions.



In [2]:
import numpy as np

In [3]:
#np.empty
#a dummy matrix of size 2x2 is initialized having random values
np.empty([2,2],dtype=int)

array([[ -158575001,  1203396911],
       [  967311297, -1146592238]])

In [5]:
#np.one
#a matrix of size 2x2 is initialized having values 1 at each cell
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [7]:
#np.zeroes
#a matrix of size 2x2 is initialized having values 0 at each cell
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?




In [8]:
#callable argument is responsible for populating each cell of the matrix whose shape is decided by the params given to the function
#depending on the condition where it comes as true, that row,col combination will be marked as true else false
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?


In [9]:
mat1 = np.array([[3,3,8],[7,7,7],[2,7,4]])
mat1

array([[3, 3, 8],
       [7, 7, 7],
       [2, 7, 4]])

In [10]:
mat1+100

array([[103, 103, 108],
       [107, 107, 107],
       [102, 107, 104]])

# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?



In [11]:
mat1 = np.array([[3,3,8],[7,7,7],[2,7,4]])
mat1

array([[3, 3, 8],
       [7, 7, 7],
       [2, 7, 4]])

In [13]:
mat1+=100

In [14]:
mat1

array([[103, 103, 108],
       [107, 107, 107],
       [102, 107, 104]])

# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?


In [35]:
mat1 = np.array(['cd','zzzz'])

In [36]:
mat1[mat1 == 'cd'] = 'abcdesdadsad'

In [37]:
mat1

array(['abcd', 'zzzz'], dtype='<U4')

# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?


In [38]:
mat1 = np.array([1,2])
mat2 = np.array([3,4])

In [41]:
np.concatenate((mat1,mat2))

array([1, 2, 3, 4])

<li>condition for joining is The arrays must have the same shape, except in the dimension corresponding to axis </li>

# Q10. What is the best way to use a Boolean array to mask another array?



<li>by using the numpy.ma module</li>

# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.



In [42]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [48]:
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

#### using stdev 

In [67]:

import timeit
import_module = "import statistics"
testcode = '''
def sample():
    return statistics.stdev(df['Fare'])
'''
print(timeit.timeit(stmt=testcode,setup=import_module))

0.06647089999933087


#### using pandas describe

In [63]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [68]:
import timeit
import_module = "import pandas"
testcode = '''
def sample():
    
    return df['Fare'].describe().loc['std']
'''
print(timeit.timeit(stmt=testcode,setup=import_module))

0.0507913000001281


# 12. What is the dimensionality of a Boolean mask-generated array?


<li> same as the source array</li>