# Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?


# Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?



<li>simple interest applies a constant rate of interest of a principal year on year</li>
<li>Whereas in case of compound interest The interest is added to the principal amount. CI is simply Interest on Interest.</li>

# Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.




<li>histogram is 2-D graph where y axis represents frqeuncy of element and x axis represent the elements</li>
<li>numpy.histogram can be used to create histograms in numpy</li>

# Q4. If necessary, how do you change the aspect ratios between the X and Y axes?


<li>if plotting using the matplotlib we can do matplotlib.axes.Axes.set_aspect</li>

# Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.



In [3]:
import numpy as np
#element wise matrix multiplication
arr1 = np.array([[5, 2],
                 [4, 4]])
arr2 = np.array([[7, 6],
                 [8, 8]])

arr = np.multiply(arr1, arr2)

In [4]:
arr

array([[35, 12],
       [32, 32]])

In [13]:
#matrix product
arr1 = np.array([[10, 2],
                 [4, 4]])
arr2 = np.array([[7, 6],
                 [8, 11]])

arr = np.matmul(arr1, arr2)

In [14]:
arr

array([[86, 82],
       [60, 68]])

In [15]:
#dot product
arr1 = np.array([[155, 2],
                 [4, 4]])
arr2 = np.array([[7, 13],
                 [8, 8]])

arr = np.dot(arr1, arr2)

In [16]:
arr

array([[1101, 2031],
       [  60,   84]])

# Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?


<li>np.pmt. However the given fucntion has been removed from numpy 1.20 onwards</li>

# Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.


In [17]:
mat1 = np.array(['cd','zzzz'])
mat1[mat1 == 'cd'] = 'abcdesdadsad'
mat1

array(['abcd', 'zzzz'], dtype='<U4')